version: '3.1'

services:

  db:
    image: mysql
    container_name: notification-api-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: 'notification-db'
      MYSQL_ROOT_PASSWORD: ${DB_MYSQL_PASSWORD}
    ports:
        - 3306:3306