version: '3.1'

services:
  db:
    image: mysql:8.1
    container_name: notification-api-db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_MYSQL_SCHEMA:-notification-db}
      MYSQL_ROOT_PASSWORD: ${DB_MYSQL_PASSWORD:-rootdb}
      TZ: America/Sao_Paulo
    ports:
      - "3306:3306"
    networks:
      - notification-lan
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  app:
    build: .
    container_name: notification-api-app
    networks:
      - notification-lan
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/${DB_MYSQL_SCHEMA:-notification-db}?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true

networks:
  notification-lan:
    driver: bridge
